name: Gradle build

on:
  push:
    branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan/dependencies
            ~/.konan/kotlin-native-prebuilt-linux-1.4.10
          key: ${{ runner.os }}-konan-1.4.10
          restore-keys: ${{ runner.os }}-konan-1.4.10
      - name: Build with Gradle
        run: ./gradlew -Dorg.gradle.daemon=false publish --build-cache
        env:
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          VCS_URL: https://github.com/CommanderTvis/kotlinx-io
          BINTRAY_USER: commandertvis

  build-osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan/dependencies
            ~/.konan/kotlin-native-prebuilt-macos-1.4.10
          key: ${{ runner.os }}-konan-1.4.10
          restore-keys: ${{ runner.os }}-konan-1.4.10
      - name: Build with Gradle
        run: ./gradlew -Dorg.gradle.daemon=false publish --build-cache
        env:
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          VCS_URL: https://github.com/CommanderTvis/kotlinx-io
          BINTRAY_USER: commandertvis
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Download JDK
        run: curl https://download.bell-sw.com/java/8u265+1/bellsoft-jdk8u265+1-windows-amd64.zip --output ./jdk.zip
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          jdkFile: ./jdk.zip
      - name: Add msys to path
        run: SETX PATH "%PATH%;C:\msys64\mingw64\bin"
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan/dependencies
            ~/.konan/kotlin-native-prebuilt-mingw-1.4.10
          key: ${{ runner.os }}-konan-1.4.10
          restore-keys: ${{ runner.os }}-konan-1.4.10
      - name: Build with Gradle
        run: ./gradlew publish --build-cache
        env:
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          VCS_URL: https://github.com/CommanderTvis/kotlinx-io
          BINTRAY_USER: commandertvis
